import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import llm from "../../config/llm.js";
import roadmapPrompt from "../../graph/roadmap/prompts/roadmap.prompt.js";
import parseJsonResponse from "../../utils/jsonParser.js";

const roadmapAgent = async (state) => {
  try {
    const resume = state.resume
      ? {
          skills: state.resume.skills || [],
          experience: state.resume.experience || [],
          projects: state.resume.projects || [],
          missingSkills: state.resume.missingSkills || [],
          score: state.resume.score || 0,
          suggestedRole: state.resume.suggestedRole || "",
          recommendations: state.resume.recommendations || [],
        }
      : null;

    const response = await llm.invoke([
      new SystemMessage(roadmapPrompt),

      new HumanMessage(`
Target Role:
${state.role}

Target Package:
${state.targetPackage}

Use Resume:
${state.useResume}

Resume:
${JSON.stringify(resume, null, 2)}
      `),
    ]);

    console.log("========== ROADMAP AI RESPONSE ==========");
    console.log(response.content);
    console.log("=========================================");

    const roadmap = parseJsonResponse(response.content);

    if (!roadmap || typeof roadmap !== "object") {
      throw new Error("Invalid roadmap generated by AI.");
    }

    const capitalize = (value = "") =>
      String(value).charAt(0).toUpperCase() +
      String(value).slice(1).toLowerCase();

    roadmap.level = capitalize(roadmap.level || "");

    roadmap.modules = Array.isArray(roadmap.modules)
      ? roadmap.modules.map((module) => ({
          title: module.title || "",
          description: module.description || "",
          difficulty: capitalize(module.difficulty || ""),
          topics: Array.isArray(module.topics) ? module.topics : [],
          duration: module.duration || "",
        }))
      : [];

    console.log(
      "========== PARSED ROADMAP =========="
    );
    console.log(JSON.stringify(roadmap, null, 2));
    console.log("====================================");

    return {
      ...state,
      roadmap,
    };
  } catch (error) {
    console.error("Error in roadmapAgent:", error);

    throw error;
  }
};

export default roadmapAgent;